version: '2'

services:
  mobir2:
    image: bio:0.0.1
    networks:
      - pmnet
    volumes:
      - ./web:/app/web
    depends_on:
      - mobirdb
    ports:
      - "5000:5000"      
    environment:
      - BUILD_CONFIG_LOC=/config
  mobirdb:
    image: mysql:5.7.22
    networks:
      - pmnet
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mobir
      MYSQL_USER: mobir
      MYSQL_PASSWORD: mobir
      MYSQL_ROOT_PASSWORD: root12345
networks:
  pmnet:
    external: true
     